# Generated by Django 2.2.5 on 2020-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointmentDate',
            field=models.CharField(max_length=500),
        ),
    ]
