# Generated by Django 2.2.5 on 2020-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.DateField()),
                ('details', models.CharField(max_length=5000)),
                ('patientId', models.CharField(max_length=20, unique=True)),
                ('appointmentId', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
