# Generated by Django 2.2.5 on 2020-04-26 15:25

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', phone_field.models.PhoneField(max_length=31)),
                ('dateOfBirth', models.CharField(max_length=200)),
                ('reminderDate', models.CharField(max_length=200)),
            ],
        ),
    ]
