# Generated by Django 2.2.5 on 2020-04-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='patientId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
